// 1. IN THE HOMEFACTORY AT THE O.DELETECOMMENT FUNCTION, WHY DO WE INSERT 1 WHEN SPLICING?

//2. IN MONGODB, WHY DOES IT RECORD THE DATE DELETED AS NULL.....SOMETIMES?

//3. MAKE SURE TO ADD 'LIKE' BOX ON COMMENTS!!!

//4. IS EXPRESS, MONGOOSE, AND PASSPORT ALL DEFINED AS MIDDLEWARE?

//5. WHAT IS THE TRANSLATIOIN FOR: 	this.salt = crypto.randomBytes(16).toString('hex'); 

//6. WHAT IS THE ORDER OF OPERATIONS FOR: $http.post('/api/Users/Register', user).success(function(res){......LINE 22 USERFACTORY.JS