// 1. IN THE HOMEFACTORY AT THE O.DELETECOMMENT FUNCTION, WHY DO WE INSERT 1 WHEN SPLICING?

//2. IN MONGODB, WHY DOES IT RECORD THE DATE DELETED AS NULL.....SOMETIMES?

//3. MAKE SURE TO ADD 'LIKE' BOX ON COMMENTS!!!